### ISSUE TITLE
Could not find instructions for valid index file

### ISSUE THREAD

**Issue by katkasian** [SamHames/hyperreal#1]
When trying to run the tool locally (command `python3 hyperreal/server.py serve `, I am encountering a ValueError (`'f"{args.index_path} is not a valid index file."`) It would be helpful to know the format required for the index file and other related steps.

**Comment by SamHames** [comment]
Oh yeah, there's nothing to describe that at all. I'll put together a worked example sometime in the next week or so.

**Comment by SamHames** [comment]
I've added a basic command line interface, and some expanded documentation to the readme - let me know how you go with that.

**Comment by SamHames** [comment]
Thanks for trying that out - sorry for the weird bugs I added in. I will actually have a lot more time from next week so hopefully we can go a little faster :)
