### ISSUE TITLE
Unclear output in the console after running hyperreal stackexchange-corpus index travel_sx.db travel_sx_index.db

### ISSUE THREAD

**Issue by katkasian** [SamHames/hyperreal#25]
After running `hyperreal stackexchange-corpus index travel_sx.db travel_sx_index.db` I am seeing several lines of output like `defaultdict(<class 'list'>, {0: ['C:\\Users\\N10980~1\\AppData\\Local\\Temp\\tmpe1_cih5z\\0']})`. I am not sure if this output is needed / helpful.

**Comment by SamHames** [comment]
Ooops, I meant to clean that up + provide something more meaningful... Will have a look next week.

**Comment by SamHames** [comment]
I've fixed this one, for now, but have opened #30 to actually put together some nicer logging functionality in the future.
